package com.pojo;
// Generated Feb 5, 2018 10:41:01 PM by Hibernate Tools 4.3.1

import java.sql.SQLException;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Registration generated by hbm2java
 */
@ManagedBean
public class Registration implements java.io.Serializable {

    private String username;
    private String firstname;
    private String lastname;
    private String password;
    private String gender;
    private String dob;
    private String nationality;
    private String email;
    private String mobileno;
    private String address;
    private String message;
    private List<Registration> allStudentShow;

    public Registration(String username, String firstname, String lastname, String password, String gender, String dob, String nationality, String email, String mobileno, String address, String message, List<Registration> allStudentShow) {
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.gender = gender;
        this.dob = dob;
        this.nationality = nationality;
        this.email = email;
        this.mobileno = mobileno;
        this.address = address;
        this.message = message;
        this.allStudentShow = allStudentShow;
    }

    public Registration() {
    }

    public Registration(String username) {
        this.username = username;
    }

    public Registration(String username, String firstname, String lastname, String password, String gender, String dob, String nationality, String email, String mobileno, String address, String message) {
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.gender = gender;
        this.dob = dob;
        this.nationality = nationality;
        this.email = email;
        this.mobileno = mobileno;
        this.address = address;
        this.message = message;
    }

    public Registration(String username, String firstname, String lastname, String password, String gender, String dob, String nationality, String email, String mobileno, String address) {
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.gender = gender;
        this.dob = dob;
        this.nationality = nationality;
        this.email = email;
        this.mobileno = mobileno;
        this.address = address;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobileno() {
        return this.mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<Registration> getAllStudentShow() {
        RegistrationDAO dao=new RegistrationDAO();
        allStudentShow=dao.showAllStudent();
        return allStudentShow;
    }

    public void setAllStudentShow(List<Registration> allStudentShow) {
        this.allStudentShow = allStudentShow;
    }

    public String doInsert() throws Exception {
        RegistrationDAO dao = new RegistrationDAO();
        boolean result = dao.doInsert(this);
        if (result) {
            return "signup";
        } else {

            return "registration";
        }
    }

    public String loginAction() throws SQLException {
        RegistrationDAO dao = new RegistrationDAO();
        boolean result = dao.doLogin(username, password);
        if (result) {
            return "originalTemplate";
        } else {
            setMessage("Login Fail");
            setUsername("");
            setPassword("");
            return "signup";
        }
    }

}
